trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: FlyDeploySecrets

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

- task: NodeTool@0
  inputs:
    versionSpec: '20.x'

- checkout: self

- script: |
    curl -L https://fly.io/install.sh | sh
    export PATH="$HOME/.fly/bin:$PATH"
    flyctl deploy --remote-only --config fly.toml
  env:
    FLY_API_TOKEN: $(FLY_API_TOKEN)
  displayName: 'Deploy to Fly.io'
