trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: BanebookingSecrets

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

- task: NodeTool@0
  inputs:
    versionSpec: '20.x'

- checkout: self

- task: Cache@2
  inputs:
    key: 'npm | "$(Agent.OS)" | Banebooking.Api/ClientApp/package-lock.json'
    restoreKeys: |
      npm | "$(Agent.OS)"
    path: 'Banebooking.Api/ClientApp/node_modules'
  displayName: 'Cache node_modules'

- script: |
    cd Banebooking.Api/ClientApp
    echo ">>> Lager .env-fil til Vite"
    echo "VITE_SUPABASE_URL=$VITE_SUPABASE_URL" > .env.production
    echo "VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY" >> .env.production
    cat .env

    npm install
    npm run build
    mkdir -p ../../wwwroot
    cp -r dist/* ../../wwwroot/
  displayName: Bygg frontend med Vite
  env:
    VITE_SUPABASE_URL: $(VITE_SUPABASE_URL)
    VITE_SUPABASE_ANON_KEY: $(VITE_SUPABASE_ANON_KEY)

- script: |
    dotnet tool install --global dotnet-ef
    export PATH="$PATH:/root/.dotnet/tools"
  displayName: 'Installer dotnet-ef'

- script: |
    dotnet ef database update --project Banebooking.Api/Banebooking.Api.csproj --startup-project Banebooking.Api/Banebooking.Api.csproj
  displayName: 'Kjør EF migrasjoner mot prod DB'
  env:
    ConnectionStrings__DefaultConnection: $(SUPABASE_CONNECTIONSTRING)

- script: |
    curl -L https://fly.io/install.sh | sh
    export PATH="$HOME/.fly/bin:$PATH"
    flyctl --version
    flyctl deploy --local-only --config fly.toml
  env:
    FLY_API_TOKEN: $(FLY_API_TOKEN)
    SUPABASE_CONNECTIONSTRING: $(SUPABASE_CONNECTIONSTRING)
  displayName: 'Deploy to Fly.io'

- script: |
    echo "Venter 15 sek før healthcheck..."
    sleep 15

    echo "Prøver maks 5 ganger på å få OK respons..."
    for i in {1..5}; do
      if curl -fsS https://banebooking-voyager.fly.dev/api/health/db; then
        echo "OK!"
        exit 0
      else
        echo "Healthcheck feilet – prøver igjen om 5 sek..."
        sleep 5
      fi
    done

    echo "Feilet etter 5 forsøk."
    exit 1
  displayName: 'Verifiser at app kjører og har DB-tilkobling'
