// <auto-generated />
using System;
using Banebooking.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Banebooking.Api.Data.Migrations
{
    [DbContext(typeof(BanebookingDbContext))]
    [Migration("20250512114100_LeggTilSubOgProviderPåBruker")]
    partial class LeggTilSubOgProviderPåBruker
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Banebooking.Api.Models.Bane", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Aktiv")
                        .HasColumnType("boolean");

                    b.Property<string>("Beskrivelse")
                        .HasColumnType("text");

                    b.Property<Guid>("KlubbId")
                        .HasColumnType("uuid");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KlubbId", "Navn")
                        .IsUnique();

                    b.ToTable("Baner");
                });

            modelBuilder.Entity("Banebooking.Api.Models.BestemmelseForBooking", b =>
                {
                    b.Property<Guid>("KlubbId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaksTimerPerDagPerBruker")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("SlotLengde")
                        .HasColumnType("interval");

                    b.Property<TimeOnly>("Stengetid")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("Åpningstid")
                        .HasColumnType("time without time zone");

                    b.HasKey("KlubbId");

                    b.ToTable("BookingRegler");
                });

            modelBuilder.Entity("Banebooking.Api.Models.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BaneId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BrukerId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Dato")
                        .HasColumnType("date");

                    b.Property<bool>("FraværVarsletTilBruker")
                        .HasColumnType("boolean");

                    b.Property<bool>("Kansellert")
                        .HasColumnType("boolean");

                    b.Property<string>("KansellertAv")
                        .HasColumnType("text");

                    b.Property<DateTime?>("KansellertTidspunkt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kommentar")
                        .HasColumnType("text");

                    b.Property<TimeOnly>("SluttTid")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("StartTid")
                        .HasColumnType("time without time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<bool>("VarsletOmKansellering")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("BrukerId");

                    b.HasIndex("BaneId", "Dato", "StartTid")
                        .IsUnique();

                    b.ToTable("Bookinger");
                });

            modelBuilder.Entity("Banebooking.Api.Models.Bruker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Epost")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Navn")
                        .HasColumnType("text");

                    b.Property<DateTime>("OpprettetTid")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sub")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Brukere");
                });

            modelBuilder.Entity("Banebooking.Api.Models.Klubb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdminEpost")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KontaktEpost")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Klubber");
                });

            modelBuilder.Entity("Banebooking.Api.Models.RapportertFravær", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kommentar")
                        .HasColumnType("text");

                    b.Property<Guid>("RapportertAvBrukerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RapportertTidspunkt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("RapportertAvBrukerId");

                    b.ToTable("FraværsRapporter");
                });

            modelBuilder.Entity("Banebooking.Api.Models.RolleITilgang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Epost")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("KlubbId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rolle")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KlubbId", "Epost")
                        .IsUnique();

                    b.ToTable("Roller");
                });

            modelBuilder.Entity("Banebooking.Api.Models.Bane", b =>
                {
                    b.HasOne("Banebooking.Api.Models.Klubb", "Klubb")
                        .WithMany("Baner")
                        .HasForeignKey("KlubbId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Klubb");
                });

            modelBuilder.Entity("Banebooking.Api.Models.BestemmelseForBooking", b =>
                {
                    b.HasOne("Banebooking.Api.Models.Klubb", "Klubb")
                        .WithOne("BookingRegel")
                        .HasForeignKey("Banebooking.Api.Models.BestemmelseForBooking", "KlubbId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Klubb");
                });

            modelBuilder.Entity("Banebooking.Api.Models.Booking", b =>
                {
                    b.HasOne("Banebooking.Api.Models.Bane", "Bane")
                        .WithMany("Bookinger")
                        .HasForeignKey("BaneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Banebooking.Api.Models.Bruker", "Bruker")
                        .WithMany("Bookinger")
                        .HasForeignKey("BrukerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Bane");

                    b.Navigation("Bruker");
                });

            modelBuilder.Entity("Banebooking.Api.Models.RapportertFravær", b =>
                {
                    b.HasOne("Banebooking.Api.Models.Booking", "Booking")
                        .WithMany("FraværsRapporter")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Banebooking.Api.Models.Bruker", "RapportertAv")
                        .WithMany("RapporterteFravær")
                        .HasForeignKey("RapportertAvBrukerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("RapportertAv");
                });

            modelBuilder.Entity("Banebooking.Api.Models.RolleITilgang", b =>
                {
                    b.HasOne("Banebooking.Api.Models.Klubb", "Klubb")
                        .WithMany("Roller")
                        .HasForeignKey("KlubbId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Klubb");
                });

            modelBuilder.Entity("Banebooking.Api.Models.Bane", b =>
                {
                    b.Navigation("Bookinger");
                });

            modelBuilder.Entity("Banebooking.Api.Models.Booking", b =>
                {
                    b.Navigation("FraværsRapporter");
                });

            modelBuilder.Entity("Banebooking.Api.Models.Bruker", b =>
                {
                    b.Navigation("Bookinger");

                    b.Navigation("RapporterteFravær");
                });

            modelBuilder.Entity("Banebooking.Api.Models.Klubb", b =>
                {
                    b.Navigation("Baner");

                    b.Navigation("BookingRegel")
                        .IsRequired();

                    b.Navigation("Roller");
                });
#pragma warning restore 612, 618
        }
    }
}
